### ISSUE TITLE
can't run the containers anymore

### ISSUE THREAD

**Issue by sternam** [eokoneyo/purifico#1]
i had no problems using this successfully before but now, I can't even get it up and running on my ubuntu 16.04 machine. here is the terminal output:

$ sudo ./start_disposable.sh 
[sudo] password for stern: 
Error: No such object: node_debug_center
 ----- Node Debug Does Not Exist. Building Now. -----
Sending build context to Docker daemon  2.306GB
Step 1/18 : FROM ubuntu:trusty
 ---> a35e70164dfb
Step 2/18 : ENV TERM xterm
 ---> Using cache
 ---> 64a76893188d
Step 3/18 : RUN apt-get update && apt-get install -y build-essential     git     ldb-3.8     lldb-3.8-dev     python-pip     linux-tools-common     linux-tools-generic
 ---> Using cache
 ---> c753306ff294
Step 4/18 : RUN pip install six
 ---> Using cache
 ---> afbcbdfcda9e
Step 5/18 : RUN cd /tmp
 ---> Using cache
 ---> 3d60d38aff3f
Step 6/18 : WORKDIR /tmp
 ---> Using cache
 ---> 4850c925f537
Step 7/18 : RUN git clone https://github.com/nodejs/llnode.git
 ---> Using cache
 ---> 6cf458844f21
Step 8/18 : RUN cd llnode
 ---> Using cache
 ---> 5dc80c85eb99
Step 9/18 : WORKDIR /tmp/llnode
 ---> Using cache
 ---> 71479a57c2ee
Step 10/18 : RUN git clone https://chromium.googlesource.com/external/gyp.git tools/gyp
 ---> Using cache
 ---> f4c827d5b63b
Step 11/18 : RUN ./gyp_llnode -Dlldb_dir=/usr/lib/llvm-3.8/
 ---> Using cache
 ---> c97b3d08cc40
Step 12/18 : RUN make -C out/ -j9
 ---> Using cache
 ---> 490752d977ea
Step 13/18 : RUN make install-linux
 ---> Running in 71f5830413a4
mkdir -p /usr/lib/lldb/plugins
cp -rf ./llnode.so /usr/lib/lldb/plugins
cp: cannot stat './llnode.so': No such file or directory
make: *** [install-linux] Error 1
The command '/bin/sh -c make install-linux' returned a non-zero code: 2
 ----- Starting Disposable Docker Container -----
Unable to find image 'node_debug_center:latest' locally
docker: Error response from daemon: pull access denied for node_debug_center, repository does not exist or may require 'docker login'.
See 'docker run --help'.
 ----- EXITED from disposable container -----
 ----- Removing Exited Containers. -----

**Comment by eokoneyo** [comment]
@sternam I haven’t actually used it in a while, it’s possible some dependency just needs updating. I’ll look into it and get back to you

**Comment by sternam** [comment]
@maziey93 thank you; I appreciate it.

**Comment by avolfson** [comment]
https://github.com/maziey93/purifico/compare/master...avolfson:master
I think I needed these changes to get it to work when I tried to use it in the summer of 2017. It was, in fact, a couple dependencies that just needed updating.

**Comment by eokoneyo** [comment]
@avolfson I will check your changes this weekend, if all checks out I'll merge them in.

**Comment by eokoneyo** [comment]
@avolfson thanks for fix, I merged it in... @sternam sorry it took forever to get this done. I'll be closing this issue.
